site_name: Open Parse
theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Parsing Text:
      - Overview: parsing-text/overview.md
  - Parsing Tables:
      - Overview: parsing-tables/overview.md
      - Unitable: parsing-tables/unitable.md
      - Pymupdf: parsing-tables/pymupdf.md
      - Table Transformer: parsing-tables/table-transformers.md
  - Processing:
      - Overview: processing/overview.md
      - Customization (Advanced): processing/customization.md
  - Visualization: visualization.md
