blank_issues_enabled: true
contact_links:
  - name: 🤔 Ask a Question
    url: "https://github.com/Filimoa/open-parse/discussions/new?category=question"
    about: Ask a question about how to use openparse using github discussions
